name: Deploy Prod

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-deploy
  cancel-in-progress: true

jobs:
  deploy-application:
    runs-on: windows-2019
    environment: test-secondary
    
    steps:

      - name: Download Azure Artifact
        run: |
          $container_name="${{ vars.AZURE_ARTIFACTS_BACKEND_STORAGE_CONTAINER }}"
          $storage_account="${{ vars.AZURE_ARTIFACTS_STORAGE_ACCOUNT }}"
          $account_key="${{ secrets.AZURE_ARTIFACTS_STORAGE_ACCOUNT_KEY }}"
          
          # List blobs in the container
          az storage blob list --account-name $storage_account --account-key $account_key --container-name $container_name --query "[].{Name:name, LastModified:properties.lastModified}" --output json | Out-File -FilePath blobs.json -Encoding utf8

          # Get the newest artifact
          $newest_file = (Get-Content blobs.json | ConvertFrom-Json | Sort-Object -Property LastModified -Descending | Select-Object -First 1).Name

          # Download the newest artifact
          az storage blob download --account-name $storage_account --account-key $account_key --container-name $container_name --name $newest_file --file Reward54.zip
          az storage blob download --account-name $storage_account --account-key $account_key --container-name $container_name --name Reward54.deploy.cmd --file Reward54.deploy.cmd
          az storage blob download --account-name $storage_account --account-key $account_key --container-name $container_name --name Reward54.SetParameters.xml --file Reward54.SetParameters.xml

      - name: Deploy application to test server
        shell: powershell
        run: .\Reward54.deploy.cmd /Y /M:https://awardco-test-beta.scm.azurewebsites.net/MSDeploy.axd /A:Basic /U:'$awardco-test__beta' /P:${{ secrets.AZURE_ARTIFACTS_DEPLOY_PWD }}
