name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      commitSha:
        description: "Github Commit Hash to Deploy"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-manual-deploy
  cancel-in-progress: true

jobs:
  deploy-application:
    runs-on: windows-2019
    environment: test-secondary
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Azure Login
        uses: Azure/login@v1.5.1
        with:
          client-id: ${{ secrets.AZURE_ARTIFACTS_CLIENT_ID}}
          tenant-id: ${{ secrets.AZURE_ARTIFACTS_TENANT_ID}}
          subscription-id: ${{ secrets.AZURE_ARTIFACTS_SUBSCRIPTION_ID}}

      - name: Download Azure Artifact
        run: |
          $container_name="${{ vars.AZURE_ARTIFACTS_BACKEND_STORAGE_CONTAINER }}"
          $storage_account="${{ vars.AZURE_ARTIFACTS_STORAGE_ACCOUNT }}"
          $account_key="${{ secrets.AZURE_ARTIFACTS_STORAGE_ACCOUNT_KEY }}"
          
          # Download the second newest artifacts
          az storage blob download --account-name $storage_account --account-key $account_key --container-name $container_name --name ${{ inputs.commitSha }}/Reward54.zip --file Reward54.zip
          az storage blob download --account-name $storage_account --account-key $account_key --container-name $container_name --name ${{ inputs.commitSha }}/Reward54.deploy.cmd --file Reward54.deploy.cmd
          az storage blob download --account-name $storage_account --account-key $account_key --container-name $container_name --name ${{ inputs.commitSha }}/Reward54.SetParameters.xml --file Reward54.SetParameters.xml

      - name: Deploy application to test server
        shell: powershell
        run: .\Reward54.deploy.cmd /Y /M:https://awardco-test-beta.scm.azurewebsites.net/MSDeploy.axd /A:Basic /U:'$awardco-test__beta' /P:${{ secrets.AZURE_ARTIFACTS_DEPLOY_PWD }}
