name: Manual Swap

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-swap
  cancel-in-progress: true

jobs:
  swap-slots:
    runs-on: windows-2019
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_ARTIFACTS_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_ARTIFACTS_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_ARTIFACTS_SUBSCRIPTION_ID }}

      - name: Swap deployment slots
        run: |
          az webapp deployment slot swap `
            --name kashby-web-app `
            --resource-group kashby-web-app `
            --slot beta `
            --target-slot production `
