# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: testing

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir testartifact
          mkdir testartifact/nestedDirectory
          touch testartifact/nestedDirectory/hello4.txt
          touch testartifact/hello.txt
          touch testartifact/hello2.txt
          echo "Hello" > testartifact/hello.txt
          echo "Hello" > testartifact/hello2.txt
          echo "Hello" > testartifact/nestedDirectory/hello4.txt

      - name: zip files
        shell: pwsh
        run: Compress-Archive -Path testartifact\* -DestinationPath testartifact${{ github.run_id }}.zip

      - name: Azure Upload
        uses: fixpoint/azblob-upload-artifact@v4
        with:
         connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
         name: backend
         container: ghartifacts
         path: testartifact${{ github.run_id }}.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: testartifact
          path: testartifact
          
  downloadArtifacts:
    runs-on: windows-2019
    environment: testing
    permissions:
      id-token: write
      contents: read
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1.5.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_ARTIFACTS }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID_ARTIFACTS }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_ARTIFACTS }}


      - name: List artifacts in Azure Storage
        id: list-artifacts
        run: |
          $container_name="ghartifacts"
          $storage_account="ghactionsartifactskashby"
          $sas_token="${{ secrets.AZURE_STORAGE_ARTIFACT_SAS_TOKEN }}"

          # List blobs in the container
          $artifacts=($(az storage blob list --account-name $storage_account --container-name $container_name --sas-token $sas_token --query "[].name" --output tsv))

          # Sort artifacts by last modified time
          $sorted_artifacts=($artifacts | Sort-Object -Descending)

          # Extract the second newest artifact
          $second_newest_artifact=$sorted_artifacts[1]

          Write-Host "second_newest_artifact=$second_newest_artifact"

          echo "##vso[task.setvariable variable=second_newest_artifact;isOutput=true]$second_newest_artifact"
 
      - name: Download second newest artifact
        run: |
          $container_name="ghartifacts"
          $storage_account="ghactionsartifactskashby"
          $artifact_name="$second_newest_artifact"
          $sas_token="${{ secrets.AZURE_STORAGE_ARTIFACT_SAS_TOKEN }}"
          
          # Create the target directory if it doesn't exist
          New-Item -ItemType Directory -Force -Path backend

          az storage blob download --account-name $storage_account --container-name $container_name --name $artifact_name --sas-token $sas_token --file testartifact.zip


      - name: Extract Downloaded artifact
        shell: powershell
        run: |
          Expand-Archive -Path testartifact.zip -DestinationPath download
          ls -la download
      # - name: Download Old Artifact
      #   uses: Legit-Labs/action-download-artifact@v2.18.0
      #   with:
      #     workflow: ${{ inputs.workflowYAML }}
      #     run_number: ${{ inputs.runNumber }}
      #     name: testartifact
      #     path: download/

      - name: echo downloaded files
        shell: powershell
        run: |
          cat download/hello.txt
          cat download/nestedDirectory/hello4.txt
