# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: testing

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir testartifact
          mkdir testartifact/nestedDirectory
          touch testartifact/nestedDirectory/hello4.txt
          touch testartifact/hello.txt
          touch testartifact/hello2.txt
          echo "Hello" > testartifact/hello.txt
          echo "Hello" > testartifact/hello2.txt
          echo "Hello" > testartifact/nestedDirectory/hello4.txt

      - name: Azure Upload
        uses: fixpoint/azblob-upload-artifact@v4
        with:
         connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
         name: testartifact
         container: ghartifacts
         path: testartifact

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: testartifact
          path: testartifact

      - name: Install Azure CLI
        uses: azure/setup-az-cli@v1
        with:
          azcliversion: 'latest'

      - name: List artifacts in Azure Storage
        id: list-artifacts
        run: |
          container_name="ghartifacts"
          storage_account="ghactionsartifactskashby"
          sas_token="?sv=2022-11-02&ss=bfqt&srt=co&sp=rwdlacupiytfx&se=2023-12-09T06:50:38Z&st=2023-12-08T22:50:38Z&spr=https&sig=QCgrkRhnAnOm0Fqe8UcNntAqVvezq6%2BfPNvkGTyMqOY%3D"

          # List blobs in the container
          artifacts=($(az storage blob list --account-name $storage_account --container-name $container_name --sas-token $sas_token --query "[].name" --output tsv))

          # Sort artifacts by last modified time
          IFS=$'\n' sorted_artifacts=($(sort -r <<<"${artifacts[*]}"))

          # Extract the second newest artifact
          second_newest_artifact="${sorted_artifacts[1]}"

          echo "::set-output name=second_newest_artifact::$second_newest_artifact"

      - name: Download second newest artifact
        run: |
          container_name="<your-container-name>"
          storage_account="<your-storage-account-name>"
          sas_token="<your-sas-token>"
          artifact_name="${{ steps.list-artifacts.outputs.second_newest_artifact }}"

          az storage blob download --account-name $storage_account --container-name $container_name --name $artifact_name --sas-token $sas_token --file $artifact_name

      # - name: Download Old Artifact
      #   uses: Legit-Labs/action-download-artifact@v2.18.0
      #   with:
      #     workflow: ${{ inputs.workflowYAML }}
      #     run_number: ${{ inputs.runNumber }}
      #     name: testartifact
      #     path: download/

      - name: echo downloaded files
        run: |
          cat download/hello.txt
          cat download/nestedDirectory/hello4.txt
